CREATE PARTITION SCHEME [DataMart_PartByYear_Scheme] 
AS PARTITION [DataMart_PartByYear] 
TO ([PRIMARY], [DATA01], [DATA01], [DATA01], [DATA01], [DATA01], [DATA01], [DATA01], [DATA01], [DATA01], [DATA01])
GO
